# WurmMapGen Properties
serverName=[QC/FR/CAN] QBC Doriath | PVE | MODS 4 K 2025

# Chemins absolus vers les fichiers téléchargés par le robot
wurmSaveDir=/home/runner/work/wurm-livemap-doriath/wurm-livemap-doriath/sqlite_db/sqlite
mapFile=/home/runner/work/wurm-livemap-doriath/wurm-livemap-doriath/sqlite_db/sqlite/top_layer.map

# Configuration des dossiers de sortie pour le site web
outputDir=/home/runner/work/wurm-livemap-doriath/wurm-livemap-doriath
templateDir=/home/runner/work/wurm-livemap-doriath/wurm-livemap-doriath/template

# Options d'affichage de la carte
enableRealtimeMarkers=false
showDeeds=true
showGuardTowers=true
showPortals=true
showStructures=true
