serverName=[QC/FR/CAN] QBC Doriath
wurmMapLocation=.
saveLocation=.
dbDir=./sqlite/
zonesDb=wurmzones.db
itemsDb=wurmitems.db
playersDb=wurmplayers.db
actualMapSize=4096
mapTileSize=256
mapMaxZoom=5
mapMinZoom=0
nativeZoom=5
markerType=2

# Correction : Activation obligatoire du réseau et passage sur le port d'enregistrement 5606
enableRealtimeMarkers=true
usePHP=false
rmiHost=nyis3.lhnode.net
rmiPort=5606

rmiPassword=
