name: Deploy Wurm Map

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Engine
        uses: actions/checkout@v4

      - name: Download Data via FTP
        run: |
          sudo apt-get install lftp
          lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.LEGION_USER }},${{ secrets.LEGION_PASS }} -p ${{ secrets.LEGION_PORT }} ${{ secrets.LEGION_HOST }}; get wurmplayers.db; get wurm.db; exit"

      - name: Generate Map
        run: |
          java -jar WurmMapGen.jar

      - name: Clone Site Web
        # C'est ici que la modification a été faite pour utiliser le jeton
        run: |
          git clone https://x-access-token:${{ secrets.MY_DEPLOY_TOKEN }}@github.com/LaTrouTe11/wurm-livemap-doriath.git

      - name: Copy Maps to Site
        run: |
          cp -r tiles/* wurm-livemap-doriath/tiles/
          # Ajoutez ici d'autres commandes de copie si nécessaire

      - name: Push to Site Web
        run: |
          cd wurm-livemap-doriath
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Mise à jour automatique de la carte"
          git push https://x-access-token:${{ secrets.MY_DEPLOY_TOKEN }}@github.com/LaTrouTe11/wurm-livemap-doriath.git main
